### ISSUE TITLE
This could be mixed with speech recognition

### ISSUE THREAD

**Issue by eorroe** [brenolf/bhaskara#1]
Haven't looked at the code yet but cool!!

**Comment by brenolf** [comment]
Thanks @eorroe! You mean native integration? I believe it'd be nice indeed to be used as a library for speech recognition on numbers, nevertheless, wouldn't it be better being a standalone library?

**Comment by eorroe** [comment]
Not asking you to implement that, just made an issue to shoutout that this would go well with speech recognition on the web etc anything js related
